Escuela2/escuela/Controllers/alumnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using escuela.Models;
using escuela.Models.ViewModels;

namespace escuela.Controllers
{
    public class alumnosController : Controller
    {
        // GET: alumnos
        public ActionResult Index()
        {
            List<ListAlumnosViewModel> lst;//es una variable
            using (escuelaEntities db = new escuelaEntities())
            {
                //colecciontipolistagenerico
                 lst = (from d in db.alumnos
                           select new ListAlumnosViewModel
                           {
                               Idalumnos = d.idalumnos,
                               Nombre = d.nombre,
                               Apellido = d.apellido
                           }).ToList();
            }
           return View(lst);//manda la lista cmo modelo
        }

        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(AlumnosViewModel model)//ejecuta el guardado //resive un parametro una sobrecarga
        {
            //si es valido realiza la programacion
            try
            {

                if (ModelState.IsValid)//valida los data notetion valida losm formatos
                {
                    //guadr los datos ne labd creando una coneccion
                    using (escuelaEntities db = new escuelaEntities())
                    {
                        var oAlumnos = new alumnos();
                        oAlumnos.nombre = model.Nombre;
                        oAlumnos.apellido = model.Apellido;
                        //agregarlo a la base de datos deberia guardarlos
                        db.alumnos.Add(oAlumnos);
                        db.SaveChanges();

                    }
                    
                    return Redirect("~/alumnos/Index"); 
                }
                return View(model);
              
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        ////////////////eliminar controlador eliminar
        /////
         public ActionResult Editar(int Id)
        {
            AlumnosViewModel model = new AlumnosViewModel();
            using (escuelaEntities db = new escuelaEntities())
            {
                var oTabla = db.alumnos.Find(Id);
                model.Nombre = oTabla.nombre;
                model.Apellido= oTabla.apellido;
               
                model.Idalumnos = oTabla.idalumnos;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(AlumnosViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (escuelaEntities db = new escuelaEntities())
                    {
                        var oTabla = db.alumnos.Find(model.Idalumnos);
                        oTabla.nombre = model.Nombre;
                        
                        oTabla.apellido = model.Apellido;

                        db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("~/alumnos/");
                }

                return View(model);


            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        /////eliminar
        
            [HttpGet]

        public ActionResult Eliminar(int Id)
        {
            AlumnosViewModel model = new AlumnosViewModel();
            using (escuelaEntities db = new escuelaEntities())
            {
                
                var Elimi= db.alumnos.Find(Id);
                db.alumnos.Remove(Elimi);//eliminar lo k encontro el find
                db.SaveChanges();
            }
            return Redirect("~/alumnos/");//llevarlo ala reaiz
        }
        /// 
        ///

    }
}

Escuela2/escuela/Views/alumnos/Index.cshtml
@model List<escuela.Models.ViewModels.ListAlumnosViewModel>
@{
    ViewBag.Title = "MIS DATOS";
}

<h2>@ViewBag.Title</h2>


<div class="row" style="text-align:right; padding:5px">
    <a href="~/alumnos/Nuevo" class="btn btn-primary">NUEVO</a>
    
</div>

    <div class="row" >
        <div class="col-md-12">
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                </tr>
                @foreach (var oElemento in Model)
                {
                    <tr>
                        <td>@oElemento.Idalumnos</td>
                        <td>@oElemento.Nombre</td>
                        <td>@oElemento.Apellido</td>

                        <td>
                            <a class="btn btn-default" href="~/alumnos/Editar/@oElemento.Idalumnos">EDITAR</a>
                            <a class="btn btn-danger" href="~/alumnos/Eliminar/@oElemento.Idalumnos">ELIMINAR</a>
                        </td>
                    </tr>
                }
            </table>
        </div>

    </div>

Escuela2/escuela/Views/alumnos/NUEVO.cshtml
@model escuela.Models.ViewModels.AlumnosViewModel
@{
    ViewBag.Title = "NUEVO";
}

<h2>@ViewBag.Title </h2>

@using (Html.BeginForm("NUEVO", "alumnos", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">

            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.Apellido)
                @Html.TextBoxFor(d => d.Apellido, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Apellido, null, new { @class = "red" })

            </div>

            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>


    </div>
}