escuela3/escuela/Models/ViewModels/ProfesorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace escuela.Models.ViewModels
{
    public class ProfesorViewModel
    {
        
            public int Idprofesor { get; set; }
         

        [Required]//data notetion para aser validaciones poner formatos
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Apellido")]//cuando no pones algo te dice km ase falta escribir el nm bre
        public string Apellido { get; set; }
    }
}

escuela3/escuela/Models/profesor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profesor()
        {
            this.actividades = new HashSet<actividades>();
            this.curso = new HashSet<curso>();
        }
    
        public int idprofesor { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividades> actividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curso> curso { get; set; }
    }
}

escuela3/escuela/Controllers/profesorController.cs
using escuela.Models;
using escuela.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using  System.Web.Mvc;


namespace escuela.Controllers
{
    public class profesorController : Controller
    {
        // GET: profesor
        public ActionResult Index()
        {
            List<ListProfesorViewModel> lst;
           
            using (escuelaEntities3 db = new escuelaEntities3())
            {
                //colecciontipolistagenerico
                lst = (from d in db.profesor
                       select new ListProfesorViewModel
                       {
                           Idprofesor = d.idprofesor,
                           Nombre = d.nombre,
                           Apellido = d.apellido
                       }).ToList();
            }
            return View(lst);//manda la lista cmo modelo

        }

        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(ProfesorViewModel model)//ejecuta el guardado //resive un parametro una sobrecarga
        {
            //si es valido realiza la programacion
            try
            {

                if (ModelState.IsValid)//valida los data notetion valida losm formatos
                {
                    //guadr los datos ne labd creando una coneccion
                    using (escuelaEntities3 db = new escuelaEntities3())
                    {
                        var oProfesor = new profesor();
                        oProfesor.nombre = model.Nombre;
                        oProfesor.apellido = model.Apellido;
                        //agregarlo a la base de datos deberia guardarlos
                        db.profesor.Add(oProfesor);
                        db.SaveChanges();

                    }

                    return Redirect("~/profesor/index");
                }
                return View(model);

            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        ////////editar
        public ActionResult Editar(int Id)
        {
            ProfesorViewModel model = new ProfesorViewModel();
            using (escuelaEntities3 db = new escuelaEntities3())
            {
                var oTabla = db.profesor.Find(Id);
                model.Nombre = oTabla.nombre;
                model.Apellido = oTabla.apellido;

                model.Idprofesor = oTabla.idprofesor;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(ProfesorViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (escuelaEntities3 db = new escuelaEntities3())
                    {
                        var oTabla = db.profesor.Find(model.Idprofesor);
                        oTabla.nombre = model.Nombre;

                        oTabla.apellido = model.Apellido;

                        db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("~/profesor/");
                }

                return View(model);


            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        ///
        //eliminar
        [HttpGet]

        public ActionResult Eliminar(int Id)
        {
            AlumnosViewModel model = new AlumnosViewModel();
            using (escuelaEntities3 db = new escuelaEntities3())
            {

                var Elimi = db.profesor.Find(Id);
                db.profesor.Remove(Elimi);//eliminar lo k encontro el find
                db.SaveChanges();
            }
            return Redirect("~/profesor/");//llevarlo ala reaiz
        }
        //
    }
}

escuela3/escuela/Views/profesor/Editar.cshtml
    @model escuela.Models.ViewModels.ProfesorViewModel
@{ 
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Editar", "profesor", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.Idprofesor)
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Apellido)
                @Html.TextBoxFor(d => d.Apellido, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Apellido, null, new { @class = "red" })
            </div>

            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>

    </div>
}

escuela3/escuela/Views/profesor/NUEVO.cshtml
@model escuela.Models.ViewModels.ProfesorViewModel
@{
    ViewBag.Title = "NUEVO";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("NUEVO", "profesor", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">

            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>

            <div>
                @Html.LabelFor(d => d.Apellido)
                @Html.TextBoxFor(d => d.Apellido, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Apellido, null, new { @class = "red" })

            </div>

            <br />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>


    </div>
}

escuela3/escuela/Views/profesor/index.cshtml
@model List<escuela.Models.ViewModels.ListProfesorViewModel>
@{
    ViewBag.Title = "Profesores";
}

<h2>@ViewBag.Title</h2>
<div class="row" style="text-align:right; padding:5px">
    <a href="~/profesor/NUEVO" class="btn btn-primary">NUEVO</a>
    <a href="~/alumnos/NUEVO" class="btn btn-primary">AGREGAR ALUMNO</a>
</div>

<div class="row">
    <dv class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Apellido</th>
            </tr>
                @foreach (var olemento in Model)
                { 
                   <tr>
                    <td>@olemento.Idprofesor</td>
                    <td>@olemento.Nombre</td>
                    <td>@olemento.Apellido</td>
                    <td>
                        <a class="btn btn-default" href="~/profesor/Editar/@olemento.Idprofesor">EDITAR</a>
                        <a class="btn btn-danger" href="~/profesor/Eliminar/@olemento.Idprofesor">ELIMINAR</a>

                    </td>
                   </tr>
                }
            </table>

    </dv>

</div>